#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#define TEXTFILE 255
#define IDR_SHADER_COMMON 10000
#define IDR_SHADER_MESH_VERT 10001
#define IDR_SHADER_MESH_FRAG 10002
